[package]
name = "build_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
[profile.release.build-override]
codegen-units = 1